apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - keycloak.yaml
  - database-bootstrap.yaml
  - refund-status-service.yaml
  - customer-ui.yaml
  - irs-simulator.yaml
  - refund-prediction-service.yaml
  - tax-policy-assistant-service.yaml
