apiVersion: apps/v1
kind: Deployment
metadata:
  name: refund-prediction-service
  namespace: refund-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refund-prediction-service
  template:
    metadata:
      labels:
        app: refund-prediction-service
    spec:
      containers:
        - name: refund-prediction-service
          image: refund-prediction-service:0.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8070
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: refund-prediction-service
  namespace: refund-platform
spec:
  selector:
    app: refund-prediction-service
  ports:
    - name: http
      port: 8070
      targetPort: http
