server:
  port: 8090

spring:
  application:
    name: irs-simulator

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      probes:
        enabled: true
